### ISSUE TITLE
Apply font-size to ul and ol content as well

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-borderzine#74]
We've set the body font size to 14px:

https://github.com/INN/umbrella-borderzine/blob/d589c9b5a644f6c1b0c1983c036b886a71de7c1e/wp-content/themes/borderzine/less/typography.less#L35-L38

But Largo provides these styles:

```css
.entry-content ol,
.entry-content ul {
    font-size: 19.55px;
}
```

The result is that list items in the story are a lot bigger than they should be:

![Screen Shot 2019-10-07 at 13 38 21 ](https://user-images.githubusercontent.com/1754187/66334914-f66ea500-e907-11e9-905a-bb160f96ccb2.png)

(This is Largo issue https://github.com/INN/largo/issues/1642 )
